CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIPO_CORRESPONDENCIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CORRESPONDENCIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIPO_IDENTIFICADOR START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAIS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROVINCIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CANTON START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DISTRITO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_UBICACION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_UNIVERSIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PERFIL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORGANIZACION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ROL_USUARIO_ORGANIZACION START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ACTIVIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COORDINADOR_ACTIVIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HORARIO_ACTIVIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PARTICIPANTE_ACTIVIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORIA_ACTIVIDAD START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TIPO_CONTROL_PROCESO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONTROL_PROCESO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOG_ERROR START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE USUARIO
(
  ID_USUARIO        NUMBER(10) DEFAULT SEQ_USUARIO.NEXTVAL NOT NULL,
  USERNAME          VARCHAR2(200)                          NOT NULL,
  PASSWORD          VARCHAR2(255)                          NOT NULL,
  RESTABLECER       CHAR(1)    DEFAULT 'N'                 NOT NULL,
  INTENTOS_FALLIDOS NUMBER(10) DEFAULT 0                   NOT NULL,
  FECHA_DESBLOQUEO  TIMESTAMP                              NULL,
  TOKEN             VARCHAR2(255)                          NULL,
  TOKEN_ESTADO      CHAR(1)    DEFAULT 'V'                 NOT NULL,
  TOKEN_EXPIRACION  TIMESTAMP                              NULL,
  FECHA_DESDE       TIMESTAMP  DEFAULT LOCALTIMESTAMP      NOT NULL,
  FECHA_HASTA       TIMESTAMP                              NULL,
  ESTADO            CHAR(1)    DEFAULT 'A'                 NOT NULL,
  CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
  CONSTRAINT UQ_USUARIO_USUARIO UNIQUE (USERNAME),
  CONSTRAINT CK_USUARIO_F_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_USUARIO_RESTABLECER CHECK (RESTABLECER IN ('N', 'S')),
  CONSTRAINT CK_USUARIO_TOKEN_ESTADO CHECK (TOKEN_ESTADO IN ('P', 'V', 'E', 'I')),
  CONSTRAINT CK_USUARIO_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE USUARIO IS 'Tabla que almacena los usuarios del sistema';
COMMENT ON COLUMN USUARIO.USERNAME IS 'Nombre de usuario único para autenticación';
COMMENT ON COLUMN USUARIO.PASSWORD IS 'Almacena el hash de la contraseña del usuario';
COMMENT ON COLUMN USUARIO.RESTABLECER IS 'Indica si el usuario debe restablecer su contraseña en el próximo inicio de sesión (S/N)';
COMMENT ON COLUMN USUARIO.FECHA_DESBLOQUEO IS 'Fecha en la que el usuario fue desbloqueado';
COMMENT ON COLUMN USUARIO.TOKEN IS 'Token de autenticación para el usuario';
COMMENT ON COLUMN USUARIO.TOKEN_ESTADO IS 'Estado del token de autenticación (P: Pendiente, V: Válido, E: Expirado, I: Inválido)';
COMMENT ON COLUMN USUARIO.TOKEN_EXPIRACION IS 'Fecha de expiración del token de autenticación';
COMMENT ON COLUMN USUARIO.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN USUARIO.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN USUARIO.ESTADO IS 'Estado del usuario: Activo (A) o Inactivo (I)';

CREATE TABLE TIPO_CORRESPONDENCIA
(
  ID_TIPO_CORRESPONDENCIA NUMBER(10) DEFAULT SEQ_TIPO_CORRESPONDENCIA.NEXTVAL NOT NULL,
  DESCRIPCION             VARCHAR2(100)                                       NOT NULL,
  FECHA_DESDE             TIMESTAMP  DEFAULT LOCALTIMESTAMP                   NOT NULL,
  FECHA_HASTA             TIMESTAMP                                           NULL,
  ESTADO                  CHAR(1)    DEFAULT 'A'                              NOT NULL,
  CONSTRAINT PK_TIPO_CORRESP PRIMARY KEY (ID_TIPO_CORRESPONDENCIA),
  CONSTRAINT CK_TIPO_CORRESP_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_TIPO_CORRESP_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE TIPO_CORRESPONDENCIA IS 'Tipos de corresponsalidad';
COMMENT ON COLUMN TIPO_CORRESPONDENCIA.DESCRIPCION IS 'Descripción del tipo de corresponsalidad (e.g., Email, Celular, Oficina)';
COMMENT ON COLUMN TIPO_CORRESPONDENCIA.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN TIPO_CORRESPONDENCIA.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN TIPO_CORRESPONDENCIA.ESTADO IS 'Estado del tipo de corresponsalidad: Activo (A) o Inactivo (I)';

CREATE TABLE CORRESPONDENCIA
(
  ID_CORRESPONDENCIA      NUMBER(10) DEFAULT SEQ_CORRESPONDENCIA.NEXTVAL NOT NULL,
  ID_USUARIO              NUMBER(10)                                     NULL,
  ID_ORGANIZACION         NUMBER(10)                                     NULL,
  ID_TIPO_CORRESPONDENCIA NUMBER(10)                                     NOT NULL,
  VALOR                   VARCHAR2(255)                                  NOT NULL,
  CONSENTIMIENTO          CHAR(1)                                        NOT NULL,
  FECHA_DESDE             TIMESTAMP  DEFAULT LOCALTIMESTAMP              NOT NULL,
  FECHA_HASTA             TIMESTAMP                                      NULL,
  ESTADO                  CHAR(1)    DEFAULT 'A'                         NOT NULL,
  CONSTRAINT PK_CORRESPONDENCIA PRIMARY KEY (ID_CORRESPONDENCIA),
  CONSTRAINT FK_CORR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT FK_CORR_ORGANIZACION FOREIGN KEY (ID_ORGANIZACION) REFERENCES ORGANIZACION (ID_ORGANIZACION),
  CONSTRAINT FK_CORRESP_TIPO FOREIGN KEY (ID_TIPO_CORRESPONDENCIA) REFERENCES TIPO_CORRESPONDENCIA (ID_TIPO_CORRESPONDENCIA),
  CONSTRAINT CK_CORR_ENTIDAD CHECK ((ID_USUARIO IS NOT NULL AND ID_ORGANIZACION IS NULL) OR (ID_USUARIO IS NULL AND ID_ORGANIZACION IS NOT NULL)),
  CONSTRAINT CK_CORRESP_CONSENTIMIENTO CHECK (CONSENTIMIENTO IN ('S', 'N')),
  CONSTRAINT CK_CORRESP_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_CORRESPONDENCIA_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE CORRESPONDENCIA IS 'Tabla de correspondencia de datos para usuarios y organizaciones';
COMMENT ON COLUMN CORRESPONDENCIA.ID_USUARIO IS 'Identificador del usuario (si la correspondencia es para un usuario)';
COMMENT ON COLUMN CORRESPONDENCIA.ID_ORGANIZACION IS 'Identificador de la organización (si la correspondencia es para una organización)';
COMMENT ON COLUMN CORRESPONDENCIA.ID_TIPO_CORRESPONDENCIA IS 'Tipo de correspondencia';
COMMENT ON COLUMN CORRESPONDENCIA.VALOR IS 'Valor de la correspondencia';
COMMENT ON COLUMN CORRESPONDENCIA.CONSENTIMIENTO IS 'Consentimiento del usuario';
COMMENT ON COLUMN CORRESPONDENCIA.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN CORRESPONDENCIA.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN CORRESPONDENCIA.ESTADO IS 'Estado de la correspondencia: Activa (A) o Inactiva (I)';

CREATE TABLE TIPO_IDENTIFICADOR
(
  ID_IDENTIFICADOR NUMBER(10) DEFAULT SEQ_TIPO_IDENTIFICADOR.NEXTVAL NOT NULL,
  DESCRIPCION      VARCHAR2(100)                                     NOT NULL,
  FECHA_DESDE      TIMESTAMP  DEFAULT LOCALTIMESTAMP                 NOT NULL,
  FECHA_HASTA      TIMESTAMP                                         NULL,
  ESTADO           CHAR(1)    DEFAULT 'A'                            NOT NULL,
  CONSTRAINT PK_TIPO_IDENT PRIMARY KEY (ID_IDENTIFICADOR),
  CONSTRAINT CK_TIPO_IDENT_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_TIPO_IDENT_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE TIPO_IDENTIFICADOR IS 'Tipos de identificadores de usuarios';
COMMENT ON COLUMN TIPO_IDENTIFICADOR.DESCRIPCION IS 'Descripción del tipo de identificador (e.g., Cédula Física, Cédula Jurídica, DIMEX, Pasaporte)';
COMMENT ON COLUMN TIPO_IDENTIFICADOR.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN TIPO_IDENTIFICADOR.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN TIPO_IDENTIFICADOR.ESTADO IS 'Estado de la correspondencia: Activa (A) o Inactiva (I)';

CREATE TABLE PAIS
(
  ID_PAIS     NUMBER(10) DEFAULT SEQ_PAIS.NEXTVAL NOT NULL,
  NOMBRE      VARCHAR2(100)                       NOT NULL,
  FECHA_DESDE TIMESTAMP  DEFAULT LOCALTIMESTAMP   NOT NULL,
  FECHA_HASTA TIMESTAMP                           NULL,
  ESTADO      CHAR(1)    DEFAULT 'A'              NOT NULL,
  CONSTRAINT PK_PAIS PRIMARY KEY (ID_PAIS),
  CONSTRAINT UQ_PAIS_NOMBRE UNIQUE (NOMBRE),
  CONSTRAINT CK_PAIS_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_PAIS_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE PAIS IS 'Tabla que almacena los países';
COMMENT ON COLUMN PAIS.NOMBRE IS 'Nombre del país';
COMMENT ON COLUMN PAIS.ESTADO IS 'Estado del país: Activa (A) o Inactiva (I)';
COMMENT ON COLUMN PAIS.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN PAIS.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN PAIS.ESTADO IS 'Estado de la correspondencia: Activa (A) o Inactiva (I)';

CREATE TABLE PROVINCIA
(
  ID_PAIS      NUMBER(10)                               NOT NULL,
  ID_PROVINCIA NUMBER(10) DEFAULT SEQ_PROVINCIA.NEXTVAL NOT NULL,
  CODIGO       VARCHAR2(2)                              NOT NULL,
  NOMBRE       VARCHAR2(100)                            NOT NULL,
  FECHA_DESDE  TIMESTAMP  DEFAULT LOCALTIMESTAMP        NOT NULL,
  FECHA_HASTA  TIMESTAMP                                NULL,
  ESTADO       CHAR(1)    DEFAULT 'A'                   NOT NULL,
  CONSTRAINT PK_PROVINCIA PRIMARY KEY (ID_PAIS, ID_PROVINCIA),
  CONSTRAINT FK_PROVINCIA_PAIS FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS),
  CONSTRAINT UQ_PROVINCIA_PAIS_COD UNIQUE (ID_PAIS, CODIGO),
  CONSTRAINT UQ_PROVINCIA_PAIS_NOM UNIQUE (ID_PAIS, NOMBRE),
  CONSTRAINT CK_PROVINCIA_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_PROVINCIA_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE PROVINCIA IS 'Tabla que almacena las provincias de cada país';
COMMENT ON COLUMN PROVINCIA.ID_PAIS IS 'Identificador del país al que pertenece la provincia';
COMMENT ON COLUMN PROVINCIA.ID_PROVINCIA IS 'Identificador único de la provincia dentro del país';
COMMENT ON COLUMN PROVINCIA.CODIGO IS 'Código único de la provincia dentro del país';
COMMENT ON COLUMN PROVINCIA.NOMBRE IS 'Nombre de la provincia';
COMMENT ON COLUMN PROVINCIA.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN PROVINCIA.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN PROVINCIA.ESTADO IS 'Estado de la provincia: Activa (A) o Inactiva (I)';

CREATE TABLE CANTON
(
  ID_PAIS      NUMBER(10)                            NOT NULL,
  ID_PROVINCIA NUMBER(10)                            NOT NULL,
  ID_CANTON    NUMBER(10) DEFAULT SEQ_CANTON.NEXTVAL NOT NULL,
  CODIGO       VARCHAR2(2)                           NOT NULL,
  NOMBRE       VARCHAR2(100)                         NOT NULL,
  FECHA_DESDE  TIMESTAMP  DEFAULT LOCALTIMESTAMP     NOT NULL,
  FECHA_HASTA  TIMESTAMP                             NULL,
  ESTADO       CHAR(1)    DEFAULT 'A'                NOT NULL,
  CONSTRAINT PK_CANTON PRIMARY KEY (ID_PAIS, ID_PROVINCIA, ID_CANTON),
  CONSTRAINT FK_CANTON_PROVINCIA FOREIGN KEY (ID_PAIS, ID_PROVINCIA) REFERENCES PROVINCIA (ID_PAIS, ID_PROVINCIA),
  CONSTRAINT UQ_CANTON_PROV_COD UNIQUE (ID_PAIS, ID_PROVINCIA, CODIGO),
  CONSTRAINT UQ_CANTON_PROV_NOM UNIQUE (ID_PAIS, ID_PROVINCIA, NOMBRE),
  CONSTRAINT CK_CANTON_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_CANTON_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE CANTON IS 'Tabla que almacena los cantones de cada provincia';
COMMENT ON COLUMN CANTON.ID_PAIS IS 'Identificador del país al que pertenece el cantón';
COMMENT ON COLUMN CANTON.ID_PROVINCIA IS 'Identificador de la provincia a la que pertenece el cantón';
COMMENT ON COLUMN CANTON.ID_CANTON IS 'Identificador único del cantón dentro de la provincia';
COMMENT ON COLUMN CANTON.CODIGO IS 'Código único del cantón dentro de la provincia';
COMMENT ON COLUMN CANTON.NOMBRE IS 'Nombre del cantón';
COMMENT ON COLUMN CANTON.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN CANTON.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN CANTON.ESTADO IS 'Estado del cantón: Activa (A) o Inactiva (I)';

CREATE TABLE DISTRITO
(
  ID_PAIS      NUMBER(10)                              NOT NULL,
  ID_PROVINCIA NUMBER(10)                              NOT NULL,
  ID_CANTON    NUMBER(10)                              NOT NULL,
  ID_DISTRITO  NUMBER(10) DEFAULT SEQ_DISTRITO.NEXTVAL NOT NULL,
  CODIGO       VARCHAR2(2)                             NOT NULL,
  NOMBRE       VARCHAR2(100)                           NOT NULL,
  FECHA_DESDE  TIMESTAMP  DEFAULT LOCALTIMESTAMP       NOT NULL,
  FECHA_HASTA  TIMESTAMP                               NULL,
  ESTADO       CHAR(1)    DEFAULT 'A'                  NOT NULL,
  CONSTRAINT PK_DISTRITO PRIMARY KEY (ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
  CONSTRAINT FK_DISTRITO_CANTON FOREIGN KEY (ID_PAIS, ID_PROVINCIA, ID_CANTON) REFERENCES CANTON (ID_PAIS, ID_PROVINCIA, ID_CANTON),
  CONSTRAINT UQ_DISTRITO_CANTON_COD UNIQUE (ID_PAIS, ID_PROVINCIA, ID_CANTON, CODIGO),
  CONSTRAINT UQ_DISTRITO_CANTON_NOM UNIQUE (ID_PAIS, ID_PROVINCIA, ID_CANTON, NOMBRE),
  CONSTRAINT CK_DISTRITO_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_DISTRITO_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE DISTRITO IS 'Tabla que almacena los distritos de cada cantón';
COMMENT ON COLUMN DISTRITO.ID_PAIS IS 'Identificador del país al que pertenece el distrito';
COMMENT ON COLUMN DISTRITO.ID_PROVINCIA IS 'Identificador de la provincia a la que pertenece el distrito';
COMMENT ON COLUMN DISTRITO.ID_CANTON IS 'Identificador del cantón al que pertenece el distrito';
COMMENT ON COLUMN DISTRITO.ID_DISTRITO IS 'Identificador único del distrito dentro del cantón';
COMMENT ON COLUMN DISTRITO.CODIGO IS 'Código único del distrito dentro del cantón';
COMMENT ON COLUMN DISTRITO.NOMBRE IS 'Nombre del distrito';
COMMENT ON COLUMN DISTRITO.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN DISTRITO.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN DISTRITO.ESTADO IS 'Estado del distrito: Activa (A) o Inactiva (I)';

CREATE TABLE UBICACION
(
  ID_UBICACION  NUMBER(10) DEFAULT SEQ_UBICACION.NEXTVAL NOT NULL,
  ID_PAIS       NUMBER(10)                               NOT NULL,
  ID_PROVINCIA  NUMBER(10)                               NULL,
  ID_CANTON     NUMBER(10)                               NULL,
  ID_DISTRITO   NUMBER(10)                               NULL,
  DIRECCION     VARCHAR2(255)                            NULL,
  CODIGO_POSTAL VARCHAR2(10)                             NULL,
  LATITUD       NUMBER(9, 6)                             NULL,
  LONGITUD      NUMBER(9, 6)                             NULL,
  FECHA_DESDE   TIMESTAMP  DEFAULT LOCALTIMESTAMP        NOT NULL,
  FECHA_HASTA   TIMESTAMP                                NULL,
  ESTADO        CHAR(1)    DEFAULT 'A'                   NOT NULL,
  CONSTRAINT PK_UBICACION PRIMARY KEY (ID_UBICACION),
  CONSTRAINT FK_UBIC_DISTRITO FOREIGN KEY (ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO) REFERENCES DISTRITO (ID_PAIS, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
  CONSTRAINT CK_UBIC_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_UBIC_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE UBICACION IS 'Tabla que almacena las ubicaciones de los usuarios';
COMMENT ON COLUMN UBICACION.ID_UBICACION IS 'Identificador único de la ubicación';
COMMENT ON COLUMN UBICACION.ID_PAIS IS 'Identificador del país de la ubicación';
COMMENT ON COLUMN UBICACION.ID_PROVINCIA IS 'Identificador de la provincia de la ubicación';
COMMENT ON COLUMN UBICACION.ID_CANTON IS 'Identificador del cantón de la ubicación';
COMMENT ON COLUMN UBICACION.ID_DISTRITO IS 'Identificador del distrito de la ubicación';
COMMENT ON COLUMN UBICACION.DIRECCION IS 'Dirección detallada de la ubicación';
COMMENT ON COLUMN UBICACION.CODIGO_POSTAL IS 'Código postal de la ubicación';
COMMENT ON COLUMN UBICACION.LATITUD IS 'Latitud geográfica de la ubicación';
COMMENT ON COLUMN UBICACION.LONGITUD IS 'Longitud geográfica de la ubicación';
COMMENT ON COLUMN UBICACION.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN UBICACION.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN UBICACION.ESTADO IS 'Estado de la ubicación: Activa (A) o Inactiva (I)';

CREATE TABLE UNIVERSIDAD
(
  ID_UNIVERSIDAD NUMBER(10) DEFAULT SEQ_UNIVERSIDAD.NEXTVAL NOT NULL,
  NOMBRE         VARCHAR2(255)                              NOT NULL,
  SIGLAS         VARCHAR2(20)                               NOT NULL,
  FECHA_DESDE    TIMESTAMP  DEFAULT LOCALTIMESTAMP          NOT NULL,
  FECHA_HASTA    TIMESTAMP                                  NULL,
  ESTADO         CHAR(1)    DEFAULT 'A'                     NOT NULL,
  CONSTRAINT PK_UNIVERSIDAD PRIMARY KEY (ID_UNIVERSIDAD),
  CONSTRAINT CK_UNIVERSIDAD_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_UNIVERSIDAD_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE UNIVERSIDAD IS 'Tabla que almacena las universidades';
COMMENT ON COLUMN UNIVERSIDAD.ID_UNIVERSIDAD IS 'Identificador único de la universidad';
COMMENT ON COLUMN UNIVERSIDAD.NOMBRE IS 'Nombre de la universidad';
COMMENT ON COLUMN UNIVERSIDAD.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN UNIVERSIDAD.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN UNIVERSIDAD.ESTADO IS 'Estado de la universidad: Activa (A) o Inactiva (I)';

CREATE TABLE PERFIL
(
  ID_PERFIL        NUMBER(10) DEFAULT SEQ_PERFIL.NEXTVAL NOT NULL,
  ID_USUARIO       NUMBER(10)                            NOT NULL,
  ID_UBICACION     NUMBER(10)                            NOT NULL,
  ID_IDENTIFICADOR NUMBER(10)                            NOT NULL,
  ID_UNIVERSIDAD   NUMBER(10)                            NULL,
  IDENTIFICACION   VARCHAR2(100)                         NOT NULL,
  NOMBRE           VARCHAR2(100)                         NOT NULL,
  APELLIDO_P       VARCHAR2(100)                         NOT NULL,
  APELLIDO_M       VARCHAR2(100)                         NULL,
  FECHA_NACIMIENTO DATE                                  NOT NULL,
  CARRERA          VARCHAR2(100)                         NULL,
  BIBLIOGRAFIA     VARCHAR2(2000)                        NULL,
  FECHA_DESDE      TIMESTAMP  DEFAULT LOCALTIMESTAMP     NOT NULL,
  FECHA_HASTA      TIMESTAMP                             NULL,
  ESTADO           CHAR(1)    DEFAULT 'A'                NOT NULL,
  CONSTRAINT PK_PERFIL PRIMARY KEY (ID_PERFIL),
  CONSTRAINT FK_PERFIL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT UQ_PERFIL_USU_IDENT UNIQUE (ID_USUARIO, ID_IDENTIFICADOR),
  CONSTRAINT FK_PERFIL_IDENT FOREIGN KEY (ID_IDENTIFICADOR) REFERENCES TIPO_IDENTIFICADOR (ID_IDENTIFICADOR),
  CONSTRAINT FK_PERFIL_UBIC FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION (ID_UBICACION),
  CONSTRAINT FK_PERFIL_UNIVERSIDAD FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD (ID_UNIVERSIDAD),
  CONSTRAINT CK_PERFIL_BIO_LEN CHECK (LENGTH(BIBLIOGRAFIA) <= 2000),
  CONSTRAINT CK_PERFIL_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_PERFIL_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE PERFIL IS 'Tabla que almacena los perfiles de los usuarios';
COMMENT ON COLUMN PERFIL.ID_PERFIL IS 'Identificador único del perfil';
COMMENT ON COLUMN PERFIL.ID_USUARIO IS 'Identificador del usuario asociado al perfil';
COMMENT ON COLUMN PERFIL.ID_UBICACION IS 'Identificador de la ubicación asociada al perfil';
COMMENT ON COLUMN PERFIL.ID_IDENTIFICADOR IS 'Identificador del tipo de identificador asociado al perfil';
COMMENT ON COLUMN PERFIL.ID_UNIVERSIDAD IS 'Identificador de la universidad asociada al perfil';
COMMENT ON COLUMN PERFIL.IDENTIFICACION IS 'Valor del identificador del usuario';
COMMENT ON COLUMN PERFIL.NOMBRE IS 'Nombre de la persona';
COMMENT ON COLUMN PERFIL.APELLIDO_P IS 'Primer apellido de la persona';
COMMENT ON COLUMN PERFIL.APELLIDO_M IS 'Segundo apellido de la persona';
COMMENT ON COLUMN PERFIL.FECHA_NACIMIENTO IS 'Fecha de nacimiento de la persona';
COMMENT ON COLUMN PERFIL.CARRERA IS 'Carrera de estudio de la persona';
COMMENT ON COLUMN PERFIL.BIBLIOGRAFIA IS 'Biografía o descripción del usuario';
COMMENT ON COLUMN PERFIL.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN PERFIL.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN PERFIL.ESTADO IS 'Estado del perfil: Activo (A) o Inactivo (I)';

CREATE TABLE ORGANIZACION
(
  ID_ORGANIZACION    NUMBER(10) DEFAULT SEQ_ORGANIZACION.NEXTVAL NOT NULL,
  ID_USUARIO_CREADOR NUMBER(10)                                  NOT NULL,
  ID_UBICACION       NUMBER(10)                                  NOT NULL,
  ID_UNIVERSIDAD     NUMBER(10)                                  NULL,
  NOMBRE             VARCHAR2(255)                               NOT NULL,
  DESCRIPCION        VARCHAR2(255)                               NOT NULL,
  FECHA_DESDE        TIMESTAMP  DEFAULT LOCALTIMESTAMP           NOT NULL,
  FECHA_HASTA        TIMESTAMP                                   NULL,
  ESTADO             CHAR(1)    DEFAULT 'A'                      NOT NULL,
  CONSTRAINT PK_ORGANIZACION PRIMARY KEY (ID_ORGANIZACION),
  CONSTRAINT FK_ORG_UBIC FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION (ID_UBICACION),
  CONSTRAINT FK_ORG_USUARIO FOREIGN KEY (ID_USUARIO_CREADOR) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT FK_ORG_UNIVERSIDAD FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD (ID_UNIVERSIDAD),
  CONSTRAINT CK_ORG_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_ORG_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE ORGANIZACION IS 'Tabla que almacena las organizaciones registradas en el sistema';
COMMENT ON COLUMN ORGANIZACION.ID_ORGANIZACION IS 'Identificador único de la organización';
COMMENT ON COLUMN ORGANIZACION.ID_USUARIO_CREADOR IS 'Identificador del usuario que creó la organización';
COMMENT ON COLUMN ORGANIZACION.ID_UBICACION IS 'Identificador de la ubicación de la organización';
COMMENT ON COLUMN ORGANIZACION.NOMBRE IS 'Nombre de la organización';
COMMENT ON COLUMN ORGANIZACION.DESCRIPCION IS 'Descripción de la organización';
COMMENT ON COLUMN ORGANIZACION.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN ORGANIZACION.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN ORGANIZACION.ESTADO IS 'Estado de la organización: Activo (A) o Inactivo (I)';

CREATE TABLE ROL
(
  ID_ROL      NUMBER(10) DEFAULT SEQ_ROL.NEXTVAL NOT NULL,
  NOMBRE      VARCHAR2(100)                      NOT NULL,
  FECHA_DESDE TIMESTAMP  DEFAULT LOCALTIMESTAMP  NOT NULL,
  FECHA_HASTA TIMESTAMP                          NULL,
  ESTADO      CHAR(1)    DEFAULT 'A'             NOT NULL,
  CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL),
  CONSTRAINT UQ_ROL_NOMBRE UNIQUE (NOMBRE),
  CONSTRAINT CK_ROL_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_ROL_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE ROL IS 'Roles de los usuarios';
COMMENT ON COLUMN ROL.ID_ROL IS 'Identificador del rol';
COMMENT ON COLUMN ROL.NOMBRE IS 'Nombre del rol (ADMINISTRADOR, COORDINADOR, ASISTENTE)';
COMMENT ON COLUMN ROL.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN ROL.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN ROL.ESTADO IS 'Estado del rol: Activo (A) o Inactivo (I)';

CREATE TABLE ROL_USUARIO_ORGANIZACION
(
  ID_ROL_USUARIO_ORGANIZACION NUMBER(10) DEFAULT SEQ_ROL_USUARIO_ORGANIZACION.NEXTVAL NOT NULL,
  ID_ORGANIZACION             NUMBER(10)                                              NOT NULL,
  ID_USUARIO_ASIGNADO         NUMBER(10)                                              NOT NULL,
  ID_USUARIO_ADMINISTRADOR    NUMBER(10)                                              NOT NULL,
  ID_ROL                      NUMBER(10)                                              NOT NULL,
  ES_ACTIVO                   CHAR(1)    DEFAULT 'A'                                  NOT NULL,
  FECHA_DESDE                 TIMESTAMP  DEFAULT LOCALTIMESTAMP                       NOT NULL,
  FECHA_HASTA                 TIMESTAMP                                               NULL,
  ESTADO                      CHAR(1)    DEFAULT 'A'                                  NOT NULL,
  CONSTRAINT PK_RUO PRIMARY KEY (ID_ROL_USUARIO_ORGANIZACION, ID_ORGANIZACION, ID_USUARIO_ASIGNADO, ID_ROL),
  CONSTRAINT UQ_RUO UNIQUE (ID_ORGANIZACION, ID_USUARIO_ASIGNADO, ID_ROL),
  CONSTRAINT FK_RUO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL),
  CONSTRAINT FK_RUO_USU_ASIG FOREIGN KEY (ID_USUARIO_ASIGNADO) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT FK_RUO_USU_ADMIN FOREIGN KEY (ID_USUARIO_ADMINISTRADOR) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT FK_RUO_ORG FOREIGN KEY (ID_ORGANIZACION) REFERENCES ORGANIZACION (ID_ORGANIZACION),
  CONSTRAINT CK_RUO_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_RUO_ES_ACTIVO CHECK (ES_ACTIVO IN ('A', 'I')),
  CONSTRAINT CK_RUO_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE ROL_USUARIO_ORGANIZACION IS 'Tabla que relaciona los usuarios con sus organizaciones y sus roles';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.ID_ROL_USUARIO_ORGANIZACION IS 'Identificador del registro';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.ID_ORGANIZACION IS 'Identificador de la organización';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.ID_USUARIO_ASIGNADO IS 'Identificador del usuario asignado';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.ID_USUARIO_ADMINISTRADOR IS 'Identificador del usuario administrador';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.ID_ROL IS 'Identificador del rol';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.ES_ACTIVO IS 'Indica si la asignación del rol está activa (A) o inactiva (I).';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN ROL_USUARIO_ORGANIZACION.ESTADO IS 'Estado del registro: Activo (A) o Inactivo (I) para borrado lógico.';

CREATE TABLE CATEGORIA_ACTIVIDAD
(
  ID_CATEGORIA_ACTIVIDAD NUMBER(10) DEFAULT SEQ_CATEGORIA_ACTIVIDAD.NEXTVAL NOT NULL,
  NOMBRE                 VARCHAR2(100)                                      NOT NULL,
  FECHA_DESDE            TIMESTAMP  DEFAULT LOCALTIMESTAMP                  NOT NULL,
  FECHA_HASTA            TIMESTAMP                                          NULL,
  ESTADO                 CHAR(1)    DEFAULT 'A'                             NOT NULL,
  CONSTRAINT PK_CAT_ACT PRIMARY KEY (ID_CATEGORIA_ACTIVIDAD),
  CONSTRAINT UQ_CAT_ACT_NOMBRE UNIQUE (NOMBRE),
  CONSTRAINT CK_CAT_ACT_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_CAT_ACT_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE CATEGORIA_ACTIVIDAD IS 'Tabla que almacena las categorías de las actividades';
COMMENT ON COLUMN CATEGORIA_ACTIVIDAD.NOMBRE IS 'Nombre de la categoría de actividad';
COMMENT ON COLUMN CATEGORIA_ACTIVIDAD.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN CATEGORIA_ACTIVIDAD.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN CATEGORIA_ACTIVIDAD.ESTADO IS 'Estado de la categoría de actividad: Activa (A) o Inactiva (I)';

CREATE TABLE ACTIVIDAD
(
  ID_ACTIVIDAD       NUMBER(10) DEFAULT SEQ_ACTIVIDAD.NEXTVAL NOT NULL,
  ID_ORGANIZACION    NUMBER(10)                               NOT NULL,
  ID_USUARIO_CREADOR NUMBER(10)                               NOT NULL,
  ID_CATEGORIA       NUMBER(10)                               NOT NULL,
  ID_UBICACION       NUMBER(10)                               NOT NULL,
  NOMBRE             VARCHAR2(100)                            NOT NULL,
  DESCRIPCION        VARCHAR2(1000)                           NOT NULL,
  FECHA_INICIO       TIMESTAMP                                NULL,
  FECHA_FIN          TIMESTAMP                                NULL,
  HORAS              NUMBER(10)                               NULL,
  CUPOS              NUMBER(10)                               NOT NULL,
  SITUACION          CHAR(1)                                  NOT NULL,
  FECHA_DESDE        TIMESTAMP  DEFAULT LOCALTIMESTAMP        NOT NULL,
  FECHA_HASTA        TIMESTAMP                                NULL,
  ESTADO             CHAR(1)    DEFAULT 'A'                   NOT NULL,
  CONSTRAINT PK_ACTIVIDAD PRIMARY KEY (ID_ACTIVIDAD),
  CONSTRAINT UQ_ACT_ORG UNIQUE (ID_ORGANIZACION, ID_ACTIVIDAD),
  CONSTRAINT FK_ACT_ORG FOREIGN KEY (ID_ORGANIZACION) REFERENCES ORGANIZACION (ID_ORGANIZACION),
  CONSTRAINT FK_ACT_USUARIO FOREIGN KEY (ID_USUARIO_CREADOR) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT FK_ACT_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_ACTIVIDAD (ID_CATEGORIA_ACTIVIDAD),
  CONSTRAINT FK_ACT_UBIC FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION (ID_UBICACION),
  CONSTRAINT CK_ACT_SITUACION CHECK (SITUACION IN ('I', 'P', 'C', 'F', 'A')),
  CONSTRAINT CK_ACT_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_ACT_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE ACTIVIDAD IS 'Tabla que almacena las actividades registradas en el sistema';
COMMENT ON COLUMN ACTIVIDAD.ID_ACTIVIDAD IS 'Identificador único de la actividad';
COMMENT ON COLUMN ACTIVIDAD.ID_ORGANIZACION IS 'Identificador de la organización que crea la actividad';
COMMENT ON COLUMN ACTIVIDAD.ID_USUARIO_CREADOR IS 'Identificador del usuario que crea la actividad';
COMMENT ON COLUMN ACTIVIDAD.ID_CATEGORIA IS 'Identificador de la categoría de la actividad';
COMMENT ON COLUMN ACTIVIDAD.ID_UBICACION IS 'Identificador de la ubicación de la actividad';
COMMENT ON COLUMN ACTIVIDAD.NOMBRE IS 'Nombre de la actividad';
COMMENT ON COLUMN ACTIVIDAD.DESCRIPCION IS 'Descripción de la actividad';
COMMENT ON COLUMN ACTIVIDAD.FECHA_INICIO IS 'Fecha de inicio de la actividad';
COMMENT ON COLUMN ACTIVIDAD.FECHA_FIN IS 'Fecha de finalización de la actividad';
COMMENT ON COLUMN ACTIVIDAD.HORAS IS 'Número de horas de la actividad';
COMMENT ON COLUMN ACTIVIDAD.CUPOS IS 'Número de cupos disponibles para la actividad';
COMMENT ON COLUMN ACTIVIDAD.SITUACION IS 'Situación de la actividad: Iniciada (I), Publicada (P), Cancelada (C), Finalizada (F), Anulada (A)';
COMMENT ON COLUMN ACTIVIDAD.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN ACTIVIDAD.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN ACTIVIDAD.ESTADO IS 'Estado de la actividad: Activa (A) o Inactiva (I)';

CREATE TABLE COORDINADOR_ACTIVIDAD
(
  ID_COORDINADOR_ACTIVIDAD NUMBER(10) DEFAULT SEQ_COORDINADOR_ACTIVIDAD.NEXTVAL NOT NULL,
  ID_ORGANIZACION          NUMBER(10)                                           NOT NULL,
  ID_ACTIVIDAD             NUMBER(10)                                           NOT NULL,
  ID_USUARIO_COORDINADOR   NUMBER(10)                                           NOT NULL,
  FECHA_DESDE              TIMESTAMP  DEFAULT LOCALTIMESTAMP                    NOT NULL,
  FECHA_HASTA              TIMESTAMP                                            NULL,
  ESTADO                   CHAR(1)    DEFAULT 'A'                               NOT NULL,
  CONSTRAINT PK_COORD_ACT PRIMARY KEY (ID_COORDINADOR_ACTIVIDAD, ID_ORGANIZACION, ID_ACTIVIDAD),
  CONSTRAINT FK_COORD_ACT_ORG FOREIGN KEY (ID_ORGANIZACION) REFERENCES ORGANIZACION (ID_ORGANIZACION),
  CONSTRAINT FK_COORD_ACT_ACT FOREIGN KEY (ID_ORGANIZACION, ID_ACTIVIDAD) REFERENCES ACTIVIDAD (ID_ORGANIZACION, ID_ACTIVIDAD),
  CONSTRAINT FK_COORD_ACT_USU FOREIGN KEY (ID_USUARIO_COORDINADOR) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT CK_COORD_ACT_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_COORD_ACT_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE COORDINADOR_ACTIVIDAD IS 'Tabla que relaciona los coordinadores con las actividades';
COMMENT ON COLUMN COORDINADOR_ACTIVIDAD.ID_COORDINADOR_ACTIVIDAD IS 'Identificador del registro';
COMMENT ON COLUMN COORDINADOR_ACTIVIDAD.ID_ORGANIZACION IS 'Identificador de la organización';
COMMENT ON COLUMN COORDINADOR_ACTIVIDAD.ID_ACTIVIDAD IS 'Identificador de la actividad';
COMMENT ON COLUMN COORDINADOR_ACTIVIDAD.ID_USUARIO_COORDINADOR IS 'Identificador del usuario coordinador';
COMMENT ON COLUMN COORDINADOR_ACTIVIDAD.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN COORDINADOR_ACTIVIDAD.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN COORDINADOR_ACTIVIDAD.ESTADO IS 'Estado del registro: Activo (A) o Inactivo (I)';

CREATE TABLE HORARIO_ACTIVIDAD
(
  ID_HORARIO_ACTIVIDAD NUMBER(10) DEFAULT SEQ_HORARIO_ACTIVIDAD.NEXTVAL NOT NULL,
  ID_ORGANIZACION      NUMBER(10)                                       NOT NULL,
  ID_ACTIVIDAD         NUMBER(10)                                       NOT NULL,
  ID_USUARIO           NUMBER(10)                                       NOT NULL,
  FECHA                DATE                                             NOT NULL,
  HORA_INICIO          TIMESTAMP                                        NOT NULL,
  HORA_FIN             TIMESTAMP                                        NOT NULL,
  DESCRIPCION          VARCHAR2(255)                                    NULL,
  SITUACION            CHAR(1)                                          NOT NULL,
  FECHA_DESDE          TIMESTAMP  DEFAULT LOCALTIMESTAMP                NOT NULL,
  FECHA_HASTA          TIMESTAMP                                        NULL,
  ESTADO               CHAR(1)    DEFAULT 'A'                           NOT NULL,
  CONSTRAINT PK_HOR_ACT PRIMARY KEY (ID_HORARIO_ACTIVIDAD, ID_ORGANIZACION, ID_ACTIVIDAD),
  CONSTRAINT FK_HOR_ACT_ORG FOREIGN KEY (ID_ORGANIZACION) REFERENCES ORGANIZACION (ID_ORGANIZACION),
  CONSTRAINT FK_HOR_ACT_ACT FOREIGN KEY (ID_ORGANIZACION, ID_ACTIVIDAD) REFERENCES ACTIVIDAD (ID_ORGANIZACION, ID_ACTIVIDAD),
  CONSTRAINT FK_HOR_ACT_USU FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT CK_HOR_ACT_HORA CHECK (HORA_INICIO < HORA_FIN),
  CONSTRAINT CK_HOR_ACT_SITUACION CHECK (SITUACION IN ('I', 'P', 'C', 'F', 'A')),
  CONSTRAINT CK_HOR_ACT_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_HOR_ACT_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE HORARIO_ACTIVIDAD IS 'Tabla que almacena los horarios de las actividades';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.ID_HORARIO_ACTIVIDAD IS 'Identificador único del horario de la actividad';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.ID_ORGANIZACION IS 'Identificador de la organización que crea el horario';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.ID_ACTIVIDAD IS 'Identificador de la actividad';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.ID_USUARIO IS 'Identificador del usuario que crea el horario';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.FECHA IS 'Fecha del horario de la actividad';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.HORA_INICIO IS 'Hora de inicio del horario de la actividad';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.HORA_FIN IS 'Hora de fin del horario de la actividad';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.DESCRIPCION IS 'Descripción del horario de la actividad';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.SITUACION IS 'Situación del horario de la actividad: Iniciada (I), Publicada (P), Cancelada (C), Finalizada (F), Anulada (A)';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN HORARIO_ACTIVIDAD.ESTADO IS 'Estado del registro: Activo (A) o Inactivo (I)';

CREATE TABLE PARTICIPANTE_ACTIVIDAD
(
  ID_PARTICIPANTE_ACTIVIDAD NUMBER(10) DEFAULT SEQ_PARTICIPANTE_ACTIVIDAD.NEXTVAL NOT NULL,
  ID_ORGANIZACION           NUMBER(10)                                            NOT NULL,
  ID_ACTIVIDAD              NUMBER(10)                                            NOT NULL,
  ID_HORARIO_ACTIVIDAD      NUMBER(10)                                            NOT NULL,
  ID_USUARIO_VOLUNTARIO     NUMBER(10)                                            NOT NULL,
  FECHA_INSCRIPCION         TIMESTAMP                                             NOT NULL,
  FECHA_RETIRO              TIMESTAMP                                             NULL,
  SITUACION                 CHAR(1)                                               NOT NULL,
  FECHA_DESDE               TIMESTAMP  DEFAULT LOCALTIMESTAMP                     NOT NULL,
  FECHA_HASTA               TIMESTAMP                                             NULL,
  ESTADO                    CHAR(1)    DEFAULT 'A'                                NOT NULL,
  CONSTRAINT PK_PART_ACT PRIMARY KEY (ID_PARTICIPANTE_ACTIVIDAD, ID_ACTIVIDAD, ID_USUARIO_VOLUNTARIO),
  CONSTRAINT FK_PART_ACT_ORG FOREIGN KEY (ID_ORGANIZACION) REFERENCES ORGANIZACION (ID_ORGANIZACION),
  CONSTRAINT FK_PART_ACT_ACT FOREIGN KEY (ID_ORGANIZACION, ID_ACTIVIDAD) REFERENCES ACTIVIDAD (ID_ORGANIZACION, ID_ACTIVIDAD),
  CONSTRAINT FK_PART_ACT_HOR FOREIGN KEY (ID_HORARIO_ACTIVIDAD, ID_ORGANIZACION, ID_ACTIVIDAD) REFERENCES HORARIO_ACTIVIDAD (ID_HORARIO_ACTIVIDAD, ID_ORGANIZACION, ID_ACTIVIDAD),
  CONSTRAINT FK_PART_ACT_USU FOREIGN KEY (ID_USUARIO_VOLUNTARIO) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT CK_PART_ACT_RETIRO CHECK (FECHA_RETIRO IS NULL OR FECHA_RETIRO > FECHA_INSCRIPCION),
  CONSTRAINT CK_PART_ACT_SIT CHECK (SITUACION IN ('I', 'A', 'R', 'C', 'F')),
  CONSTRAINT CK_PART_ACT_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_PART_ACT_EST CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE PARTICIPANTE_ACTIVIDAD IS 'Tabla que relaciona los participantes con las actividades';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.ID_PARTICIPANTE_ACTIVIDAD IS 'Identificador del registro';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.ID_ORGANIZACION IS 'Identificador de la organización';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.ID_ACTIVIDAD IS 'Identificador de la actividad';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.ID_HORARIO_ACTIVIDAD IS 'Identificador del horario de la actividad';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.ID_USUARIO_VOLUNTARIO IS 'Identificador del usuario voluntario participante';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.FECHA_INSCRIPCION IS 'Fecha de inscripción del participante en la actividad';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.FECHA_RETIRO IS 'Fecha de retiro del participante de la actividad';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.SITUACION IS 'Situación del participante en la actividad: Inicial (I), Activo (A), Retirado (R), Cancelado (C), Finalizado (F)';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN PARTICIPANTE_ACTIVIDAD.ESTADO IS 'Estado del registro: Activo (A) o Inactivo (I)';

CREATE TABLE CERTIFICADO_PARTICIPACION
(
  ID_CERTIFICACION          RAW(16)   DEFAULT SYS_GUID()     NOT NULL,
  ID_PARTICIPANTE_ACTIVIDAD NUMBER(10)                       NOT NULL,
  ID_ACTIVIDAD              NUMBER(10)                       NOT NULL,
  ID_ORGANIZACION           NUMBER(10)                       NOT NULL,
  ID_USUARIO_VOLUNTARIO     NUMBER(10)                       NOT NULL,
  FECHA_EMISION             TIMESTAMP                        NOT NULL,
  HORAS_TOTALES             NUMBER(10)                       NOT NULL,
  DIAS_TOTALES              NUMBER(10)                       NOT NULL,
  FECHA_PRIMERA_ASISTENCIA  TIMESTAMP                        NOT NULL,
  FECHA_ULTIMA_ASISTENCIA   TIMESTAMP                        NOT NULL,
  SITUACION                 CHAR(1)                          NOT NULL,
  OBSERVACIONES             VARCHAR2(500)                    NULL,
  DOCUMENTO                 BLOB                             NULL,
  FECHA_ENVIO               TIMESTAMP                        NULL,
  INTENTOS_ENVIO            NUMBER(10)                       NULL,
  ULTIMO_INTENTO_ENVIO      TIMESTAMP                        NULL,
  ULTIMO_ERROR_ENVIO        VARCHAR2(2000)                   NULL,
  FECHA_DESDE               TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  FECHA_HASTA               TIMESTAMP                        NULL,
  ESTADO                    CHAR(1)   DEFAULT 'A'            NOT NULL,
  CONSTRAINT PK_CERT_PART PRIMARY KEY (ID_CERTIFICACION),
  CONSTRAINT FK_CERT_PART_ACT FOREIGN KEY (ID_ORGANIZACION, ID_ACTIVIDAD) REFERENCES ACTIVIDAD (ID_ORGANIZACION, ID_ACTIVIDAD),
  CONSTRAINT FK_CERT_PART_USU FOREIGN KEY (ID_USUARIO_VOLUNTARIO) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT FK_CERT_PART_PART FOREIGN KEY (ID_PARTICIPANTE_ACTIVIDAD, ID_ACTIVIDAD, ID_USUARIO_VOLUNTARIO) REFERENCES PARTICIPANTE_ACTIVIDAD (ID_PARTICIPANTE_ACTIVIDAD, ID_ACTIVIDAD, ID_USUARIO_VOLUNTARIO),
  CONSTRAINT UQ_CERT_PART UNIQUE (ID_PARTICIPANTE_ACTIVIDAD, ID_ACTIVIDAD, ID_USUARIO_VOLUNTARIO),
  CONSTRAINT CK_CERT_PART_SIT CHECK (SITUACION IN ('P', 'G', 'E', 'A', 'C')),
  CONSTRAINT CK_CERT_PART_VIG CHECK (FECHA_DESDE <= FECHA_HASTA),
  CONSTRAINT CK_CERT_PART_EST CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE CERTIFICADO_PARTICIPACION IS 'Tabla que almacena los certificados de participación de los voluntarios';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.ID_CERTIFICACION IS 'Identificador único del certificado de participación';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.ID_PARTICIPANTE_ACTIVIDAD IS 'Identificador del participante en la actividad';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.ID_ACTIVIDAD IS 'Identificador de la actividad';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.ID_ORGANIZACION IS 'Identificador de la organización que emite el certificado';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.ID_USUARIO_VOLUNTARIO IS 'Identificador del usuario voluntario al que se le emite el certificado';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.FECHA_EMISION IS 'Fecha de emisión del certificado';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.HORAS_TOTALES IS 'Número total de horas certificadas';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.DIAS_TOTALES IS 'Número total de días certificados';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.FECHA_PRIMERA_ASISTENCIA IS 'Fecha de la primera asistencia del voluntario';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.FECHA_ULTIMA_ASISTENCIA IS 'Fecha de la última asistencia del voluntario';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.SITUACION IS 'Situación del certificado: Pendiente (P), Generado (G), Emitido (E), Completado (C), Anulado (A)';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.OBSERVACIONES IS 'Observaciones adicionales sobre el certificado';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.DOCUMENTO IS 'Documento del certificado en formato BLOB';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.FECHA_ENVIO IS 'Fecha en que se envió el certificado por correo electrónico';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.INTENTOS_ENVIO IS 'Número de intentos de envío del certificado por correo electrónico';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.ULTIMO_INTENTO_ENVIO IS 'Fecha del último intento de envío del certificado por correo electrónico';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.ULTIMO_ERROR_ENVIO IS 'Mensaje del último error ocurrido durante el envío del certificado por correo electrónico';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.FECHA_DESDE IS 'Fecha desde la cual el registro es accesible';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.FECHA_HASTA IS 'Fecha hasta la cual el registro es accesible';
COMMENT ON COLUMN CERTIFICADO_PARTICIPACION.ESTADO IS 'Estado del certificado: Activo (A) o Inactivo (I)';

/**
 * CONTROL DE PROCESOS
 */
CREATE TABLE TIPO_CONTROL
(
  ID_TIPO_CONTROL NUMBER(10) DEFAULT SEQ_TIPO_CONTROL_PROCESO.NEXTVAL NOT NULL,
  NOMBRE          VARCHAR2(100)                                       NOT NULL,
  ESTADO          CHAR(1)    DEFAULT 'A'                              NOT NULL,
  CONSTRAINT PK_TIPO_CONTROL PRIMARY KEY (ID_TIPO_CONTROL),
  CONSTRAINT CK_TIPO_CONTROL_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

COMMENT ON TABLE TIPO_CONTROL IS 'Tabla que almacena los tipos de control de procesos';
COMMENT ON COLUMN TIPO_CONTROL.ID_TIPO_CONTROL IS 'Identificador único del tipo de control de proceso';
COMMENT ON COLUMN TIPO_CONTROL.NOMBRE IS 'Nombre del tipo de control de proceso (e.g., Generación de Certificados, envío de correos)';
COMMENT ON COLUMN TIPO_CONTROL.ESTADO IS 'Estado del tipo de control de proceso: Activo (A) o Inactivo (I)';

CREATE TABLE CONTROL_PROCESO_GENERACION_CER
(
  ID_CONTROL             NUMBER(10) DEFAULT SEQ_CONTROL_PROCESO.NEXTVAL NOT NULL,
  TIPO_CONTROL           NUMBER(10)                                     NOT NULL,
  INICIO_EJECUCION       TIMESTAMP  DEFAULT LOCALTIMESTAMP              NOT NULL,
  FIN_EJECUCION          TIMESTAMP  DEFAULT LOCALTIMESTAMP              NOT NULL,
  ACTIVIDADES_PROCESADAS NUMBER(10) DEFAULT 0                           NULL,
  CERTIFICADOS_GENERADOS NUMBER(10) DEFAULT 0                           NULL,
  CORREOS_ENVIADOS       NUMBER(10) DEFAULT 0                           NULL,
  ESTADO                 CHAR(1)    DEFAULT 'S'                         NOT NULL,
  ERROR_MENSAJE          VARCHAR2(2000)                                 NULL,
  CONSTRAINT PK_CONTROL PRIMARY KEY (ID_CONTROL),
  CONSTRAINT FK_CONTROL_TIPO_CONTROL FOREIGN KEY (TIPO_CONTROL) REFERENCES TIPO_CONTROL (ID_TIPO_CONTROL),
  CONSTRAINT CK_CONTROL_ESTADO CHECK (ESTADO IN ('S', 'C', 'E', 'P'))
);

COMMENT ON TABLE CONTROL_PROCESO_GENERACION_CER IS 'Tabla que almacena el control de los procesos de generación de certificados y envío de correos';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.ID_CONTROL IS 'Identificador único del control de proceso';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.TIPO_CONTROL IS 'Identificador del tipo de control de proceso';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.INICIO_EJECUCION IS 'Fecha y hora de inicio de la ejecución del proceso';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.FIN_EJECUCION IS 'Fecha y hora de finalización de la ejecución del proceso';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.ACTIVIDADES_PROCESADAS IS 'Número de actividades procesadas en el proceso';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.CERTIFICADOS_GENERADOS IS 'Número de certificados generados en el proceso';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.CORREOS_ENVIADOS IS 'Número de correos enviados en el proceso';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.ESTADO IS 'Estado del proceso: Espera (S), Completado (C), Error (E), Procesando (P)';
COMMENT ON COLUMN CONTROL_PROCESO_GENERACION_CER.ERROR_MENSAJE IS 'Mensaje de error en caso de que el proceso falle';

CREATE TABLE LOG_ERROR
(
  ID_LOG_ERROR NUMBER(10)   DEFAULT SEQ_LOG_ERROR.NEXTVAL NOT NULL,
  USUARIO      VARCHAR2(30) DEFAULT USER                  NOT NULL,
  FECHA        TIMESTAMP    DEFAULT LOCALTIMESTAMP        NOT NULL,
  PROGRAMA     VARCHAR2(100)                              NOT NULL,
  LINEA        NUMBER(10)                                 NULL,
  CLASE        VARCHAR2(100)                              NULL,
  CODIGO       NUMBER                                     NULL,
  MENSAJE      VARCHAR2(2000)                             NOT NULL,
  STACK        VARCHAR2(2000)                             NULL,
  BACKTRACE    VARCHAR2(2000)                             NULL,
  CONSTRAINT PK_LOG_ERROR PRIMARY KEY (ID_LOG_ERROR)
);

COMMENT ON TABLE LOG_ERROR IS 'Tabla que almacena los errores producidos en el sistema';
COMMENT ON COLUMN LOG_ERROR.ID_LOG_ERROR IS 'Identificador único del error registrado';
COMMENT ON COLUMN LOG_ERROR.USUARIO IS 'Usuario que experimentó el error';
COMMENT ON COLUMN LOG_ERROR.FECHA IS 'Fecha y hora en que ocurrió el error';
COMMENT ON COLUMN LOG_ERROR.PROGRAMA IS 'Nombre del programa o procedimiento donde ocurrió el error';
COMMENT ON COLUMN LOG_ERROR.LINEA IS 'Número de línea del código donde ocurrió el error';
COMMENT ON COLUMN LOG_ERROR.CLASE IS 'Clase del error: NEGOCIO, TECNICO, VALIDACION';
COMMENT ON COLUMN LOG_ERROR.CODIGO IS 'Código del error: SQLCODE o código de negocio';
COMMENT ON COLUMN LOG_ERROR.MENSAJE IS 'Mensaje descriptivo del error';
COMMENT ON COLUMN LOG_ERROR.STACK IS 'Pila de llamadas del error formateada';
COMMENT ON COLUMN LOG_ERROR.BACKTRACE IS 'Rastreo de llamadas del error formateada';
